"""Offline scoring harness.

Reproduces, for one task, everything the validator does between "miner replies"
and "score lands in the EMA":

    1. ground truth built with the *upstream* prompts (never the miner's)
    2. ``validate_tag_set``  - clean, 20-sample cull, 50-char truncate, the
       malformed-keyword LLM screen, and the raw-membership filter that
       silently deletes non-normalized tags
    3. re-embedding of the surviving tags with text-embedding-3-small
    4. ``GroundTruthTagSimilarityScoringMechanism`` (or the NoPenalty variant)

Fidelity notes, stated up front because they bound every number this produces:

* Ground truth is generated by *our* OpenAI account, not the validator's. Same
  model, same prompt, same temperature - but LLM output is not deterministic, so
  a strategy's absolute score carries ~+/-0.01 of GT noise. Comparisons between
  strategies on the *same* GT are paired and much tighter than that.
* Real validators may run a different OPENAI_MODEL. gpt-5.2 is the committed
  default (llm_openai.py:14) and Discord confirms legit validators run defaults.
* Enrichment lines in production come from live web search. Where the corpus has
  none we can synthesize them; GT and miner always receive the *same* lines, so
  the comparison stays honest.
"""

from __future__ import annotations

import asyncio
import random
import statistics
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Sequence

import numpy as np

from conversationgenome.utils.Utils import Utils
from sn33 import llm, prompts, scoring
from sn33.replica import clean_like_validator
from sn33.tags import normalize_all

GT_MODEL_DEFAULT = "gpt-5.2"


# --------------------------------------------------------------------------
# Task cases
# --------------------------------------------------------------------------

@dataclass
class Case:
    """One scored unit of work, mirroring what a miner receives."""

    kind: str
    guid: str
    # conversation: full lines for GT, window lines for the miner
    full_lines: List[tuple] = field(default_factory=list)
    window_lines: List[tuple] = field(default_factory=list)
    # document tasks: the miner gets the same text GT was built from
    document: str = ""
    enrichment: List[str] = field(default_factory=list)
    # survey
    question: str = ""
    comment: str = ""
    # optional reference tags shipped with the corpus (ReadyAI historical tags)
    reference_tags: List[str] = field(default_factory=list)
    coding: bool = False

    def miner_window(self) -> List[tuple]:
        return self.window_lines if self.kind == "conversation_tagging" else [(0, self.document)]


def convo_xml(lines: Sequence[tuple]) -> str:
    """Match Utils.generate_convo_xml's shape (<pN>text</pN>)."""
    xml = "<conversation id='bench'>"
    for line in lines:
        if len(line) != 2:
            continue
        xml += f"<p{line[0]}>{line[1]}</p{line[0]}>"
    xml += "</conversation>"
    return xml


# --------------------------------------------------------------------------
# Ground truth  (validator side)
# --------------------------------------------------------------------------

@dataclass
class GroundTruth:
    tags: List[str]
    vectors: Dict[str, List[float]]
    target: Optional[np.ndarray]
    sets: List[List[str]] = field(default_factory=list)

    def ok(self) -> bool:
        return bool(self.tags) and self.target is not None


async def build_ground_truth(case: Case, model: str = GT_MODEL_DEFAULT, use_cache: bool = True) -> GroundTruth:
    """Run the validator's own ground-truth path for this case.

    Conversation ground truth uses the FULL conversation - that asymmetry
    (validator sees everything, miner sees a 10-line window) is the central
    difficulty of the task and the harness must preserve it.
    """
    async def tags_of(prompt: str) -> List[str]:
        # temperature=None -> the API default (1.0), which is what the validator
        # runs: upstream llm_openai.basic_prompt sets no temperature at all.
        # Ground truth therefore carries genuine sampling variance, and a miner
        # cannot reproduce it exactly even with an identical prompt.
        return clean_like_validator(
            await llm.chat(prompt, model=model, timeout=90, temperature=None, use_cache=use_cache, salt="gt")
        )

    if case.kind == "conversation_tagging":
        doc_prompt = prompts.gt_conversation(convo_xml(case.full_lines), coding=case.coding)
        enrich_prompt = lambda t: prompts.gt_enrichment(t, coding=case.coding)  # noqa: E731
    elif case.kind == "webpage_metadata_generation":
        doc_prompt = prompts.gt_website(case.document, coding=case.coding)
        enrich_prompt = lambda t: prompts.gt_enrichment(t, coding=case.coding)  # noqa: E731
    elif case.kind == "named_entities_extraction":
        doc_prompt = prompts.gt_transcript_ner(case.document)
        enrich_prompt = prompts.gt_enrichment_ner
    elif case.kind == "skill_generation":
        doc_prompt = prompts.gt_skill(case.document)
        enrich_prompt = prompts.gt_enrichment
    elif case.kind == "survey_tagging":
        # No LLM anywhere: ground truth is the literal selected_choices.
        gt_tags = [t.strip().lower() for t in case.reference_tags if t and t.strip()]
        vecs = await llm.embed(gt_tags)
        return GroundTruth(gt_tags, vecs, scoring.neighborhood({k: v for k, v in vecs.items()}), [gt_tags])
    else:
        raise ValueError(f"unknown case kind {case.kind}")

    jobs = [tags_of(doc_prompt)] + [tags_of(enrich_prompt(t)) for t in case.enrichment]
    results = await asyncio.gather(*jobs, return_exceptions=True)
    sets = [r for r in results if not isinstance(r, BaseException) and r]
    if not sets:
        return GroundTruth([], {}, None, [])

    must_combine = case.kind != "conversation_tagging" or len(sets) > 1
    if must_combine:
        combined = await tags_of(prompts.gt_combine(sets))
        gt_tags = combined or sets[0]
    else:
        gt_tags = sets[0]

    # The validator embeds through get_vector_embeddings_set, which re-cleans
    # tags first - so the vector dict is keyed by CLEANED tags while
    # metadata.tags keeps the raw strings. Scoring uses raw tags for the
    # both/unique split and cleaned tags for the vectors. Reproduce both.
    cleaned = Utils.get_clean_tag_set(gt_tags)
    vecs = await llm.embed(cleaned)
    return GroundTruth(gt_tags, vecs, scoring.neighborhood(vecs), sets)


# --------------------------------------------------------------------------
# Miner-side post-processing  (validator side, applied to our answer)
# --------------------------------------------------------------------------

async def validate_tag_set(
    tags: Sequence[str], model: str = GT_MODEL_DEFAULT, ner: bool = False, seed: int = 0, use_cache: bool = True
) -> List[str]:
    """Replicate LlmLib.validate_tag_set / validate_named_entities_tag_set."""
    if not tags:
        return []
    clean = Utils.get_clean_tag_set(list(tags))
    if len(clean) >= 20:
        # random.sample keeps 20 - which 20 is luck, so the bench must model it.
        clean = [clean[i] for i in random.Random(seed).sample(range(len(clean)), 20)]
    if ner:
        return clean
    clean = [t[:50] for t in clean]

    raw = await llm.chat(
        prompts.upstream("validate_tags.j2", tags_string=", ".join(clean)),
        model=model,
        timeout=90,
        temperature=None,   # validator-side call, same default sampling
        use_cache=use_cache,
        salt="validate",
    )
    if not raw:
        # basic_prompt returns None on API failure and validate_tag_set then
        # does len(None) -> TypeError inside the validator. Treat as total loss.
        return []
    lowered = raw.lower()
    cut = lowered.find("malformed")
    good = lowered[0:cut].replace("good english keywords:", "").replace("***", "").replace("\n", "").strip()
    valid = Utils.get_clean_tag_set(good.split(","))
    return [t for t in valid if t in tags]


@dataclass
class Verdict:
    final: float
    adjusted: float
    penalties: List[str]
    n_submitted: int
    n_survived: int
    n_unique: int
    n_both: int
    detail: dict = field(default_factory=dict)


async def score_answer(
    gt: GroundTruth,
    tags: Sequence[str],
    kind: str,
    model: str = GT_MODEL_DEFAULT,
    seed: int = 0,
    use_cache: bool = True,
) -> Verdict:
    """Score one miner answer exactly as the validator would."""
    ner = kind == "named_entities_extraction"
    penalties = not ner                       # NoPenalty mechanism for NER
    min_tags = 3 if kind in ("conversation_tagging", "webpage_metadata_generation", "skill_generation") else 1

    if not gt.ok():
        return Verdict(0.0, 0.0, ["no_ground_truth"], len(tags), 0, 0, 0)

    survived = await validate_tag_set(tags, model=model, ner=ner, seed=seed, use_cache=use_cache)
    if not survived:
        return Verdict(0.0, 0.0, ["all_tags_dropped"], len(tags), 0, 0, 0)

    vecs = await llm.embed(Utils.get_clean_tag_set(survived), use_cache=use_cache)
    res = scoring.score_tags(gt.tags, gt.target, survived, vecs, penalties=penalties, min_tags=min_tags, seed=seed)
    return Verdict(
        final=res["final"],
        adjusted=res["adjusted"],
        penalties=res["penalties"],
        n_submitted=len(tags),
        n_survived=len(survived),
        n_unique=res["n_unique"],
        n_both=res["n_both"],
        detail=res,
    )


# --------------------------------------------------------------------------
# Reporting
# --------------------------------------------------------------------------

def summarize(name: str, verdicts: Sequence[Verdict]) -> dict:
    finals = [v.final for v in verdicts]
    if not finals:
        return {"name": name, "n": 0}
    pen = [p for v in verdicts for p in v.penalties]
    return {
        "name": name,
        "n": len(finals),
        "mean": statistics.mean(finals),
        "median": statistics.median(finals),
        "stdev": statistics.pstdev(finals) if len(finals) > 1 else 0.0,
        "min": min(finals),
        "max": max(finals),
        "zeros": sum(1 for f in finals if f <= 0.0),
        "mean_tags": statistics.mean([v.n_survived for v in verdicts]),
        "penalty_rate": len([v for v in verdicts if v.penalties]) / len(verdicts),
        "penalties": {p: pen.count(p) for p in sorted(set(pen))},
    }


def paired_delta(a: Sequence[Verdict], b: Sequence[Verdict], iters: int = 10000, seed: int = 0) -> dict:
    """Bootstrap the paired difference b - a over the same cases.

    Strategies are always evaluated on identical ground truth, so pairing
    removes GT noise - without it a 0.01 difference is unreadable.
    """
    diffs = [y.final - x.final for x, y in zip(a, b)]
    if not diffs:
        return {}
    rng = random.Random(seed)
    means = []
    n = len(diffs)
    for _ in range(iters):
        means.append(sum(diffs[rng.randrange(n)] for _ in range(n)) / n)
    means.sort()
    lo = means[int(0.025 * iters)]
    hi = means[int(0.975 * iters)]
    return {
        "delta": statistics.mean(diffs),
        "ci95": (lo, hi),
        "wins": sum(1 for d in diffs if d > 0),
        "losses": sum(1 for d in diffs if d < 0),
        "significant": lo > 0 or hi < 0,
    }
