"""Replicate the validator's ground-truth pipeline from the miner's own input.

The scoring target is the mean of the embeddings of the validator's
ground-truth tags. We cannot see those tags - but for three of the five task
types we are handed the *exact text they were generated from*:

    WebpageMetadataGenerationTaskBundle.py:160,186
        website_markdown = parsed_json['website_markdown'][:1000]
        ... GT built from it ...
        self.input.data.lines = [(0, website_markdown)] + enrichment_lines   <-- miner input

    NamedEntitiesExtractionTaskBundle.py:87,119     (transcript_text[:1000])
    SkillGenerationTaskBundle.py:157,162            (skill_markdown[:1000])

So running the validator's own prompts over that same text reproduces its tag
set closely, and the mean of those tags' embeddings is a direct estimate of the
target vector.

Conversation tagging is the partial case: ground truth comes from the FULL
conversation (<=300 lines) while the miner sees one <=10-line window
(ConversationTaggingTaskBundle.py:185-198). The enrichment lines, however, are
passed through verbatim and their tags are generated by the same upstream
prompt - so that slice of the target is still exactly reproducible, and the
window contributes a blurred version of the rest.

Survey tagging has no LLM ground truth at all: the target is the literal
`selected_choices` strings (SurveyTaggingTaskBundle.py:68), so there is nothing
to replicate and we predict instead.
"""

from __future__ import annotations

import asyncio
from collections import Counter
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Sequence, Tuple

from sn33 import llm, prompts
from sn33.tags import parse_tag_list

# Longest a deep enrichment call may hold the fan-out open after the calls the
# answer actually depends on have landed. Measured: deep fan-out reaches 3.80s
# against a shallow fan-out of 1.66s, so the deep calls need up to ~2.1s MORE
# than the shallow ones. The old value of 1.6s was smaller than that gap, so at
# the measured latencies the deep calls were always cancelled AND the grace was
# still spent - the worst of both. This is a ceiling only: the actual wait is
# clamped to whatever fan-out budget remains after the combine reserve, so a
# generous value here never eats into combine.
DEEP_GRACE_S = 4.0

# Utils.clean_tags only strips/lowercases/removes quotes - it does NOT strip
# punctuation. So ground-truth tags may contain characters a miner tag can
# never contain (a miner tag must survive get_safe_tag to be scored at all).
# That asymmetry is why exact "both" matches are only reachable on clean tags.
def clean_like_validator(raw: Optional[str]) -> List[str]:
    if not raw:
        return []
    return [t.strip().lower().replace('"', "") for t in raw.split(",") if t.strip()]


@dataclass
class Replica:
    """Predicted ground-truth tags plus the raw material used to build them."""

    tags: List[str] = field(default_factory=list)          # validator-style (may hold punctuation)
    doc_tags: List[str] = field(default_factory=list)      # main-document set
    enrichment_tags: List[List[str]] = field(default_factory=list)
    # Deeper per-enrichment-line extraction (prompts.gt_enrichment_deep).
    # CANDIDATE POOL ONLY - deliberately outside `all_sets`, so it never reaches
    # combine, `tags`, or anything downstream that estimates the target.
    deep_tags: List[str] = field(default_factory=list)
    timings: Dict[str, float] = field(default_factory=dict)
    degraded: bool = False                                  # a step failed; tags are partial

    @property
    def all_sets(self) -> List[List[str]]:
        return [s for s in [self.doc_tags, *self.enrichment_tags] if s]


def local_combine(tag_sets: Sequence[Sequence[str]], limit: int = 20) -> List[str]:
    """Cheap stand-in for the validator's combine call.

    The upstream template asks for "the most important and recurring" entities,
    capped at 20, so we rank by how many sets a tag appears in and break ties by
    first appearance. Saves a round trip when the deadline is tight.
    """
    counts: Counter = Counter()
    first_seen: Dict[str, int] = {}
    order = 0
    for tag_set in tag_sets:
        for tag in dict.fromkeys(tag_set):  # dedupe within a set
            counts[tag] += 1
            if tag not in first_seen:
                first_seen[tag] = order
                order += 1
    ranked = sorted(counts.items(), key=lambda kv: (-kv[1], first_seen[kv[0]]))
    return [t for t, _ in ranked[:limit]]


async def _tags_from_prompt(
    prompt: str, model: str, timeout: float, use_cache: bool, salt: str = "miner"
) -> List[str]:
    # salt="miner" keeps these samples distinct from the bench's ground-truth
    # calls, which render the same prompts. Without it a shared cache would
    # hand us the validator's exact answer and fake a perfect replica.
    raw = await llm.chat(prompt, model=model, timeout=timeout, use_cache=use_cache, salt=salt)
    return clean_like_validator(raw)


async def _deep_tags_from_prompt(
    prompt: str, model: str, timeout: float, use_cache: bool
) -> List[str]:
    """Parse a deep-enrichment reply into pool tags.

    Deep tags are POOL material that gets submitted, unlike predicted_gt which
    must reproduce the validator's own comma-delimited strings. A 30-tag request
    comes back as a bullet or numbered list far more often than a 10-tag one, and
    clean_like_validator (comma-only) would fuse "- a\\n- b\\n- c" into the single
    43-char tag "a b c" - lowercase, alphanumeric, so it passes normalize and the
    validator embeds the junk. parse_tag_list splits lists correctly. salt="deep"
    keeps the cache namespace separate from the shallow calls.
    """
    raw = await llm.chat(prompt, model=model, timeout=timeout, use_cache=use_cache, salt="deep")
    return parse_tag_list(raw)


async def _sampled_tags(
    prompt: str, model: str, timeout: float, use_cache: bool, samples: int
) -> List[str]:
    """Run the ground-truth prompt several times and pool the results.

    The validator generates ground truth with NO temperature set, i.e. the API
    default of 1.0 (upstream ``basic_prompt`` omits the parameter), so its tags
    are one draw from a distribution rather than a fixed answer. A single replica
    call is therefore a noisy estimate of the target.

    Pooling independent draws shrinks that noise: tags the model returns on
    every draw are the ones most likely to be in the validator's own draw, and
    they dominate the pooled centroid because they appear repeatedly. The calls
    are concurrent, so N samples cost one call's latency, not N.
    """
    if samples <= 1:
        return await _tags_from_prompt(prompt, model, timeout, use_cache)
    results = await asyncio.gather(
        *[
            _tags_from_prompt(prompt, model, timeout, use_cache, salt=f"miner{i}")
            for i in range(samples)
        ],
        return_exceptions=True,
    )
    pooled: List[str] = []
    for r in results:
        if isinstance(r, BaseException) or not r:
            continue
        pooled.extend(r)          # duplicates are deliberate: they weight the centroid
    return pooled


async def replicate(
    kind: str,
    *,
    document: str = "",
    convo_xml: str = "",
    enrichment: Sequence[str] = (),
    model: str = "gpt-5.2",
    timeout: float = 8.0,
    coding: bool = False,
    combine: str = "llm",          # "llm" | "local" | "none"
    use_cache: bool = False,
    samples: int = 1,              # independent draws of the ground-truth prompt
    deadline: float = 0.0,         # seconds left for the WHOLE replica, 0 = unbounded
    deep_enrichment: int = 0,      # >0: also extract this many tags/line into rep.deep_tags
) -> Replica:
    """Reproduce the validator's ground-truth tags for one task.

    ``kind`` is the task type discriminator: conversation_tagging,
    webpage_metadata_generation, named_entities_extraction, skill_generation.
    Never raises - a failed step yields a degraded replica.
    """
    import time as _time
    t_start = _time.perf_counter()
    rep = Replica()
    timings: Dict[str, float] = {}

    # ---- main document prompt, chosen to match the validator's own path ----
    # `deep_prompt` is None wherever the enrichment path does not use the
    # enrichment_to_metadata family - the NER template has no tag-cap line to
    # widen, so there is nothing faithful to deepen there.
    deep_prompt = None
    if kind == "conversation_tagging":
        doc_prompt = prompts.gt_conversation(convo_xml, coding=coding)
        enrich_prompt = lambda t: prompts.gt_enrichment(t, coding=coding)  # noqa: E731
        deep_prompt = lambda t: prompts.gt_enrichment_deep(t, n=deep_enrichment, coding=coding)  # noqa: E731
    elif kind == "webpage_metadata_generation":
        doc_prompt = prompts.gt_website(document, coding=coding)
        enrich_prompt = lambda t: prompts.gt_enrichment(t, coding=coding)  # noqa: E731
        deep_prompt = lambda t: prompts.gt_enrichment_deep(t, n=deep_enrichment, coding=coding)  # noqa: E731
    elif kind == "named_entities_extraction":
        doc_prompt = prompts.gt_transcript_ner(document)
        enrich_prompt = prompts.gt_enrichment_ner
    elif kind == "skill_generation":
        doc_prompt = prompts.gt_skill(document)
        enrich_prompt = prompts.gt_enrichment
        deep_prompt = lambda t: prompts.gt_enrichment_deep(t, n=deep_enrichment)  # noqa: E731
    else:
        raise ValueError(f"no ground-truth replica for task kind {kind!r}")

    # ---- every call concurrently: the validator ran them serially, we cannot ----
    jobs = [llm.timed(_sampled_tags(doc_prompt, model, timeout, use_cache, samples), "doc", timings)]
    for i, text in enumerate(enrichment):
        jobs.append(
            llm.timed(
                _tags_from_prompt(enrich_prompt(text), model, timeout, use_cache),
                f"enrich{i}",
                timings,
            )
        )

    # Deep per-line extraction is issued INSIDE the same fan-out window, but as
    # separate tasks that nothing waits on. A deep call is a bigger completion
    # (10 -> 30 tags) and measured ~1.2-1.6s slower than its shallow twin, so if
    # it were part of the gather above it could drag the whole fan-out past the
    # budget and cost us the doc tags - the answer, not an extra.
    deep_tasks: List[asyncio.Future] = []
    if deep_enrichment > 0 and deep_prompt is not None:
        try:
            deep_prompts = [deep_prompt(text) for text in enrichment]
        except ValueError:
            # Template drift: gt_enrichment_deep raises when upstream re-words the
            # tag-cap line. That loud failure is correct at the unit level, but at
            # RUNTIME it must degrade to the feature being OFF. If it escaped
            # replicate, pipeline._gather_within would turn it into a lost
            # predicted_gt and drop the answer from "ranked" to "pool" (measured
            # 0.5517 -> 0.1994). Deep tags are only extra pool material, so
            # disable them and keep the rest of the replica intact.
            deep_prompts = []
        deep_tasks = [
            asyncio.ensure_future(
                llm.timed(
                    _deep_tags_from_prompt(p, model, timeout, use_cache),
                    f"deep{i}",
                    timings,
                )
            )
            for i, p in enumerate(deep_prompts)
        ]

    # Bound the fan-out itself, so a slow enrichment call cannot consume the
    # budget the combine step still needs. `deadline > 0` (not just truthiness):
    # an exactly-expired deadline of 0.0 must NOT read as "unbounded" and hand
    # the fan-out the full timeout.
    fanout_budget = max(0.5, deadline - 2.0) if deadline > 0 else timeout

    # Wrap every job in an explicit task so a slow one can be dropped WITHOUT
    # discarding the jobs that already finished. The old code awaited a single
    # asyncio.wait_for(gather(...)): when the budget expired it cancelled the
    # whole gather, throwing away even the doc tags that had landed and dropping
    # the answer from "ranked" (~0.55) to "pool" (~0.20). asyncio.wait keeps the
    # completed results and cancels only the stragglers.
    job_tasks = [asyncio.ensure_future(j) for j in jobs]

    # One try/finally covers both task groups. asyncio.wait does NOT cancel its
    # awaitables when it is itself cancelled, so on ANY exit - normal, or an
    # external CancelledError from pipeline._gather_within landing during either
    # await below - the finally reaps every still-pending job AND deep task
    # rather than letting them outlive the replica and keep spending API budget.
    try:
        done, _pending = await asyncio.wait(job_tasks, timeout=fanout_budget)
        clean: List[List[str]] = []
        for t in job_tasks:
            ok = t in done and not t.cancelled() and t.exception() is None
            r = t.result() if ok else None
            clean.append([] if (isinstance(r, BaseException) or not r) else r)

        rep.doc_tags = clean[0]
        rep.enrichment_tags = [c for c in clean[1:] if c]
        rep.degraded = not rep.doc_tags

        # Launch the combine NOW, concurrently with the deep grace below. Its
        # inputs (all_sets = doc + per-line enrichment) are complete at this
        # point and deep_tags are deliberately not an input, so this is a pure
        # reordering: same prompt, same sets, same result - it just stops a
        # slow deep straggler from serializing in front of a ~2s combine call
        # (the mechanism behind every source=pool truncation on 2026-08-10).
        # The pre-launch budget guard and timeout mirror the sequential path
        # exactly; evaluating them earlier only ever RELAXES them, which is the
        # point - by the time the old code checked, the straggler had already
        # spent the budget.
        combine_task = None
        early_sets = rep.all_sets
        if early_sets and combine == "llm" and (
                kind != "conversation_tagging" or len(early_sets) > 1):
            c_timeout = timeout
            launch = True
            if deadline > 0:
                left = deadline - (_time.perf_counter() - t_start)
                if left < 1.2:
                    launch = False          # same guard as the sequential path
                else:
                    c_timeout = min(timeout, left)
            if launch:
                combine_task = asyncio.ensure_future(
                    llm.timed(
                        _tags_from_prompt(
                            prompts.gt_combine(early_sets), model, c_timeout, use_cache
                        ),
                        "combine",
                        timings,
                    )
                )

        # ---- LATENCY GATE ------------------------------------------------
        # Deep results are collected on the way past, never waited for beyond
        # what the fan-out had already been allotted. Grace is capped at
        # DEEP_GRACE_S AND at whatever is left of fanout_budget, so the 2.0s the
        # combine step is holding is untouchable. Since 2026-08-10 the combine
        # call RUNS CONCURRENTLY with this grace (launched just above): combine
        # never reads deep_tags (all_sets excludes them by design, pinned by
        # test_deep_tags_never_reach_the_replica_combine_input), so waiting for
        # stragglers no longer delays it - the 6.8s-deep-straggler truncations
        # of 2026-08-10 came from paying grace THEN combine sequentially.
        #
        # THE DEGRADATION PATH: a deep call that is slow, fails, or returns None
        # simply leaves rep.deep_tags shorter, and rep.deep_tags feeds ONLY the
        # candidate pool. An empty rep.deep_tags is byte-for-byte the feature
        # being off - it can never produce a truncated answer. At an 8s deadline
        # 15% of tasks were truncated and scored 0.1994 against 0.5517, so a 4%
        # rise in truncation erases the entire +0.024 the feature is worth.
        if deep_tasks:
            grace = min(DEEP_GRACE_S, fanout_budget - (_time.perf_counter() - t_start))
            if grace > 0:
                await asyncio.wait(deep_tasks, timeout=grace)
            seen = set(rep.deep_tags)
            for t in deep_tasks:
                if t.cancelled() or not t.done() or t.exception():
                    continue
                for tag in t.result() or []:
                    if tag not in seen:
                        seen.add(tag)
                        rep.deep_tags.append(tag)
    except BaseException:
        # An external cancel (pipeline deadline) or unexpected error must not
        # leave the pre-launched combine spending API budget in the background.
        if combine_task is not None and not combine_task.done():
            combine_task.cancel()
        raise
    finally:
        for t in (*job_tasks, *deep_tasks):
            if not t.done():
                t.cancel()

    rep.timings = timings

    sets = rep.all_sets
    if not sets:
        return rep

    # ---- combine, exactly where the validator combines ----
    # Conversation combines only when enrichment exists (ConversationTaggingTaskBundle.py:236);
    # webpage/NER/skill always combine.
    must_combine = kind != "conversation_tagging" or len(sets) > 1
    if not must_combine or combine == "none":
        rep.tags = sets[0]
        return rep

    if combine == "local":
        rep.tags = local_combine(sets)
        return rep

    # LLM combine: consume the task launched before the deep grace. Fallback
    # semantics are byte-identical to the old sequential call - the only
    # difference is WHEN the call started.
    if combine_task is not None:
        # llm.chat never raises past its wrapper (returns None), so like the old
        # sequential await this only ever surfaces an external CancelledError -
        # which must propagate, exactly as it did before.
        combined = await combine_task
        if combined:
            rep.tags = combined
        else:
            rep.tags = local_combine(sets)
            rep.degraded = True
        return rep

    # The combine call is the only sequential step, so it is the one that gets
    # cut off when the budget runs out. Losing it must not lose the document and
    # enrichment tags we already paid for - a union of those is a usable
    # estimate, an empty replica is not. Observed in production: a task with 6
    # enrichment lines blew the budget here and the whole replica was cancelled,
    # dropping the miner to its local-only fallback.
    if deadline > 0:
        import time as _t
        left = deadline - (_t.perf_counter() - t_start)
        if left < 1.2:
            rep.tags = local_combine(sets)
            rep.degraded = True
            rep.timings = timings
            return rep
        timeout = min(timeout, left)

    combined = await llm.timed(
        _tags_from_prompt(prompts.gt_combine(sets), model, timeout, use_cache), "combine", timings
    )
    if combined:
        rep.tags = combined
    else:  # combine failed - union is a better estimate than nothing
        rep.tags = local_combine(sets)
        rep.degraded = True
    return rep
